###
GET http://localhost:9000/api HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "nombre": "Goku",
    "cliente": "Franscisco Javier",
    "precio": 900
}

###
DELETE http://localhost:9000/api/5 HTTP/1.1

###
PUT http://localhost:9000/api/1 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Lata corona",
    "cliente": "Juan Perez",
    "precio": 500
}